### ISSUE TITLE
test_network.py fails with Python 3.8

### ISSUE THREAD

**Issue by afettouhi** [thoughtfulml/examples-in-python#22]
Hi, I am going through your book "Thoughtful Machine Learning with Python: A Test-Driven Approach" and I trying to run the code examples from Chapter 8 "Neural Networks". When I try to the unittests in test_network.py I get this error

```
Testing started at 09.33 ...
/home/af/Dokumenter/Programs/miniconda3/envs/ThoughtfulMachineLearningWithPython-py38/bin/python /opt/pycharm-professional/plugins/python/helpers/pycharm/_jb_unittest_runner.py --path "/home/af/Dokumenter/Programs/ThoughtfulMachineLearningWithPython-py38/Chapter 8/tests/test_network.py"
/home/af/Dokumenter/Programs/miniconda3/envs/ThoughtfulMachineLearningWithPython-py38/lib/python3.8/site-packages/nose_parameterized/__init__.py:6: UserWarning: The 'nose-parameterized' package has been renamed 'parameterized'. For the two step migration instructions, see: https://github.com/wolever/parameterized#migrating-from-nose-parameterized-to-parameterized (set NOSE_PARAMETERIZED_NO_WARN=1 to suppress this warning)
Launching unittests with arguments python -m unittest /home/af/Dokumenter/Programs/ThoughtfulMachineLearningWithPython-py38/Chapter 8/tests/test_network.py in /home/af/Dokumenter/Programs/ThoughtfulMachineLearningWithPython-py38/Chapter 8/tests
  warnings.warn(

Traceback (most recent call last):
  File "/opt/pycharm-professional/plugins/python/helpers/pycharm/_jb_unittest_runner.py", line 35, in <module>
    sys.exit(main(argv=args, module=None, testRunner=unittestpy.TeamcityTestRunner, buffer=not JB_DISABLE_BUFFERING))
  File "/home/af/Dokumenter/Programs/miniconda3/envs/ThoughtfulMachineLearningWithPython-py38/lib/python3.8/unittest/main.py", line 100, in __init__
    self.parseArgs(argv)
  File "/home/af/Dokumenter/Programs/miniconda3/envs/ThoughtfulMachineLearningWithPython-py38/lib/python3.8/unittest/main.py", line 147, in parseArgs
    self.createTests()
  File "/home/af/Dokumenter/Programs/miniconda3/envs/ThoughtfulMachineLearningWithPython-py38/lib/python3.8/unittest/main.py", line 158, in createTests
    self.test = self.testLoader.loadTestsFromNames(self.testNames,
  File "/home/af/Dokumenter/Programs/miniconda3/envs/ThoughtfulMachineLearningWithPython-py38/lib/python3.8/unittest/loader.py", line 220, in loadTestsFromNames
    suites = [self.loadTestsFromName(name, module) for name in names]
  File "/home/af/Dokumenter/Programs/miniconda3/envs/ThoughtfulMachineLearningWithPython-py38/lib/python3.8/unittest/loader.py", line 220, in <listcomp>
    suites = [self.loadTestsFromName(name, module) for name in names]
  File "/home/af/Dokumenter/Programs/miniconda3/envs/ThoughtfulMachineLearningWithPython-py38/lib/python3.8/unittest/loader.py", line 154, in loadTestsFromName
    module = __import__(module_name)
  File "/home/af/Dokumenter/Programs/ThoughtfulMachineLearningWithPython-py38/Chapter 8/tests/test_network.py", line 11, in <module>
    from network import Network
  File "/home/af/Dokumenter/Programs/ThoughtfulMachineLearningWithPython-py38/Chapter 8/network.py", line 2, in <module>
    import theanets
  File "/home/af/Dokumenter/Programs/miniconda3/envs/ThoughtfulMachineLearningWithPython-py38/lib/python3.8/site-packages/theanets/__init__.py", line 4, in <module>
    from .feedforward import Autoencoder, Regressor, Classifier
  File "/home/af/Dokumenter/Programs/miniconda3/envs/ThoughtfulMachineLearningWithPython-py38/lib/python3.8/site-packages/theanets/feedforward.py", line 9, in <module>
    from . import graph
  File "/home/af/Dokumenter/Programs/miniconda3/envs/ThoughtfulMachineLearningWithPython-py38/lib/python3.8/site-packages/theanets/graph.py", line 15, in <module>
    from . import layers
  File "/home/af/Dokumenter/Programs/miniconda3/envs/ThoughtfulMachineLearningWithPython-py38/lib/python3.8/site-packages/theanets/layers/__init__.py", line 1, in <module>
    from .base import *
  File "/home/af/Dokumenter/Programs/miniconda3/envs/ThoughtfulMachineLearningWithPython-py38/lib/python3.8/site-packages/theanets/layers/base.py", line 16, in <module>
    logging = climate.get_logger(__name__)
AttributeError: module 'climate' has no attribute 'get_logger'

Process finished with exit code 1

Empty suite
```

I can see it complains about the climate module but I can't figure out how to fix this. Any advice or suggestions?

**Comment by hexgnu** [comment]
Hey @afettouhi I just pushed up some changes that converted theanets to use keras and tensorflow.

Honestly these days I wouldn't recommend theanets to be used mainly cause it hasn't been updated in about 2 years.

Check out the code (which I verified is working on 3.8.3) and let me know if you have any additional questions.

Thanks!
